name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          plugin_isocalendar: true
          plugin_languages: true
          plugin_languages_indepth: yes
          commits_authoring: znhihgiasy@gmail.com
          plugin_languages_indepth_custom: nicball/eoc
          plugin_languages_details: lines, percentage
          plugin_languages_ignored: Vim Script, KakouneScript
          plugin_leetcode: true
